// Phase 0 ctest: proves golden .bin blobs reload bit-exact across the
// Python -> C++ boundary. For each entry in the generated manifest:
//   1. open the .bin, assert file size == n_elements * 4 (fp32),
//   2. recompute SHA-256 over the raw bytes and assert it equals the digest
//      Python recorded (equal digests over the byte stream => identical bytes),
//   3. reinterpret the bytes as fp32 and assert every value is finite-loadable
//      (catches endianness/truncation independently of the digest).
// Exit 0 only if all entries pass. Runs under Release and ASan/UBSan, so the
// reader itself is proven memory-clean.
//
// The manifest header is generated by tools/dump_reference.py so this test
// cannot drift from the dump and needs no JSON parser (stdlib-only rule).

#include <cinttypes>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include "golden/manifest_generated.hpp"
#include "sha256.hpp"

#ifndef DBINFER_GOLDEN_DIR
#error "DBINFER_GOLDEN_DIR must be defined by the build (path to tests/golden)"
#endif

namespace {

// Returns true on success; prints a FAIL line and returns false otherwise.
bool check_entry(const dbinfer::golden::Entry& e) {
  std::string path = std::string(DBINFER_GOLDEN_DIR) + "/" + e.relpath;

  std::FILE* f = std::fopen(path.c_str(), "rb");
  if (f == nullptr) {
    std::printf("FAIL %-20s cannot open %s\n", e.name, path.c_str());
    return false;
  }

  if (std::fseek(f, 0, SEEK_END) != 0) {
    std::printf("FAIL %-20s fseek failed\n", e.name);
    std::fclose(f);
    return false;
  }
  std::int64_t size = std::ftell(f);
  if (size < 0) {
    std::printf("FAIL %-20s ftell failed\n", e.name);
    std::fclose(f);
    return false;
  }
  std::rewind(f);

  const std::size_t expected_bytes = e.n_elements * sizeof(float);
  if (static_cast<std::size_t>(size) != expected_bytes) {
    std::printf("FAIL %-20s size %" PRId64 " != expected %zu (n_elements=%zu)\n", e.name, size,
                expected_bytes, e.n_elements);
    std::fclose(f);
    return false;
  }

  std::vector<std::uint8_t> bytes(expected_bytes);
  std::size_t got = expected_bytes == 0 ? 0 : std::fread(bytes.data(), 1, expected_bytes, f);
  std::fclose(f);
  if (got != expected_bytes) {
    std::printf("FAIL %-20s read %zu of %zu bytes\n", e.name, got, expected_bytes);
    return false;
  }

  std::string digest = dbinfer::sha256::hex_digest(bytes.data(), bytes.size());
  if (digest != e.sha256hex) {
    std::printf("FAIL %-20s sha256 %s != recorded %s\n", e.name, digest.c_str(), e.sha256hex);
    return false;
  }

  // Reinterpret as fp32 to catch endianness/truncation independently of the
  // digest. Just touch every element so UBSan sees the loads.
  volatile float sink = 0.0f;
  const std::uint8_t* p = bytes.data();
  for (std::size_t i = 0; i < e.n_elements; ++i) {
    float v;
    std::memcpy(&v, p + i * sizeof(float), sizeof(float));
    sink = v;
  }
  (void)sink;

  std::printf("PASS %-20s %zu elems  sha256=%.16s...\n", e.name, e.n_elements, digest.c_str());
  return true;
}

}  // namespace

int main() {
  constexpr std::size_t n =
      sizeof(dbinfer::golden::kEntries) / sizeof(dbinfer::golden::kEntries[0]);
  if (n == 0) {
    std::printf("FAIL manifest has zero entries\n");
    return 1;
  }

  int failures = 0;
  for (std::size_t i = 0; i < n; ++i) {
    if (!check_entry(dbinfer::golden::kEntries[i])) ++failures;
  }

  std::printf("---\n%zu golden tensors checked, %d failed\n", n, failures);
  return failures == 0 ? 0 : 1;
}
