// GENERATED by tools/dump_reference.py — do not edit by hand.
// Constexpr view of tests/golden/manifest.json for the reload test.
#ifndef DBINFER_TESTS_GOLDEN_MANIFEST_GENERATED_HPP
#define DBINFER_TESTS_GOLDEN_MANIFEST_GENERATED_HPP

#include <cstddef>

namespace dbinfer::golden {

struct Entry {
  const char *name;
  const char *relpath;
  std::size_t n_elements;
  const char *sha256hex;
};

inline constexpr Entry kEntries[] = {
    {"embedding", "embedding.bin", 5376, "2c068ba57a34a8844d3940bc5c3084e34e48cd28d5b907ef3d83790188d394e6"},
    {"rmsnorm_in", "rmsnorm_in.bin", 5376, "2c068ba57a34a8844d3940bc5c3084e34e48cd28d5b907ef3d83790188d394e6"},
    {"rmsnorm_out", "rmsnorm_out.bin", 5376, "7061b0c3a1c323df3a7431c9e829e0313b77010cf55e64920a9c245b773cea20"},
    {"rope_q_in", "rope_q_in.bin", 5376, "dfc409b27811563fef7f5a339513743f628965d295612fda1d47b2fa818f59ec"},
    {"rope_q_out", "rope_q_out.bin", 5376, "46646b9c24b480729e20c69d4d26227b423da75853398aa710705b5e2265af28"},
    {"rope_k_in", "rope_k_in.bin", 768, "46f2e2b7d0ee2ae4f1824ae7f51ecd70915c436e3be174c7e33ba278e47d4f90"},
    {"rope_k_out", "rope_k_out.bin", 768, "4d54b435770897e3233457789f98f8b609c151b06eeecdc1f07ac34ec866a383"},
    {"attn_head0_out", "attn_head0_out.bin", 384, "9189f897ecf778c3299449fd8a0d188d813859baba43923eef02ab559a3bd307"},
    {"layer0_out", "layer0_out.bin", 5376, "84cd66916c4aea4ab4718675e1a42f2bb8a03f665587e06b51c11d0b9b33f339"},
    {"swiglu_in", "swiglu_in.bin", 5376, "19d12733ece64684c21aa22bef8c750c1964e3dc111f663266a1cfe01651c928"},
    {"swiglu_out", "swiglu_out.bin", 5376, "db691f3d440f886cf096583ebead8ffd626fa903535921159b3f294d19def988"},
    {"logits", "logits.bin", 911616, "02d7178b32f6dd9e6dc75cb5c729a4dd1a8721d52802dbb4b52046066fb9738c"},
};

} // namespace dbinfer::golden

#endif // DBINFER_TESTS_GOLDEN_MANIFEST_GENERATED_HPP
