#!/usr/bin/env python3
"""Generate the tokenizer parity fixture from the pinned llama.cpp oracle.

For each fixed input (raw bytes, so invalid UTF-8 survives), runs
`llama-tokenize --ids --no-bos --no-parse-special` and records the token ids.
Emits tests/tokenizer/fixture_generated.hpp..
"""

from __future__ import annotations

import hashlib
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GGUF = os.path.join(ROOT, "tools", "llama.cpp", "models", "qwen2.5-0.5b.gguf")
TOKENIZE = os.path.join(ROOT, "tools", "llama.cpp", "build", "bin", "llama-tokenize")
OUT = os.path.join(ROOT, "tests", "tokenizer", "fixture_generated.hpp")

CASES: list[bytes] = [
    b"Hello world",
    b"hello",
    b"The quick brown fox jumps over the lazy dog.",
    b"",
    b" ",
    b"   ",
    b" leading space",
    b"trailing space ",
    b"multiple     spaces",
    b"\ttab\tseparated\t",
    b"line1\nline2\nline3",
    b"windows\r\nnewline",
    b"CamelCaseIdentifier",
    b"snake_case_name",
    b"don't can't won't",
    b"IT'S UPPER'S",
    b"123",
    b"4567890",
    b"3.14159",
    b"version 2.0.1",
    b"a1b2c3",
    b"!@#$%^&*()",
    b"punctuation, and; more: stuff?",
    b"[brackets] {braces} <angles>",
    b"path/to/some/file.txt",
    b"https://example.com/page?q=1&r=2",
    b"email@example.com",
    "café".encode(),
    "naïve résumé".encode(),
    "Über den Wolken".encode(),
    "Ñoño español".encode(),
    "Ελληνικά".encode(),
    "Привет мир".encode(),
    "你好世界".encode(),
    "こんにちは".encode(),
    "한국어 텍스트".encode(),
    "日本語のテスト".encode(),
    "中文标点，。！".encode(),
    "😀".encode(),
    "emoji 🎉 party 🚀".encode(),
    "👨‍👩‍👧‍👦 family".encode(),
    "🏳️‍🌈 flag".encode(),
    "👍🏽 skin tone".encode(),
    "mixed 日本 text 123 🎉".encode(),
    "  spaced\tCJK\n你好  ".encode(),
    b"\xff\xfe",
    b"valid\xffinvalid",
    b"\xc3\x28",
    b"\xe2\x82",
    b"tab\tand\xffbad",
]


def tokenize(data: bytes) -> list[int]:
    with tempfile.NamedTemporaryFile(delete=False) as tf:
        tf.write(data)
        path = tf.name
    try:
        res = subprocess.run(
            [
                TOKENIZE,
                "-m",
                GGUF,
                "-f",
                path,
                "--ids",
                "--no-bos",
                "--no-parse-special",
            ],
            capture_output=True,
        )
    finally:
        os.unlink(path)
    out = res.stdout.decode("utf-8", "replace")
    m = re.search(r"\[([0-9,\s]*)\]", out)
    if m is None:
        print(f"error: no id list in output for {data!r}:\n{out}", file=sys.stderr)
        sys.exit(1)
    body = m.group(1).strip()
    if not body:
        return []
    return [int(x) for x in body.split(",")]


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def cpp_bytes(data: bytes) -> str:
    return "{" + ", ".join(f"0x{b:02x}" for b in data) + "}"


def main() -> int:
    if not (os.path.exists(GGUF) and os.path.exists(TOKENIZE)):
        print("error: gguf or llama-tokenize missing", file=sys.stderr)
        return 2

    commit = "unknown"
    ver_path = os.path.join(ROOT, "tools", "LLAMACPP_VERSION")
    if os.path.exists(ver_path):
        for line in open(ver_path):
            if line.startswith("commit="):
                commit = line.split("=", 1)[1].strip()

    gguf_sha = sha256_file(GGUF)

    lines = [
        "// GENERATED by tools/gen_tokenizer_fixture.py — do not edit by hand.",
        f"// oracle: llama-tokenize (llama.cpp commit {commit})",
        f"// gguf sha256: {gguf_sha}",
        "// args: --ids --no-bos --no-parse-special",
        "#ifndef DBINFER_TESTS_TOKENIZER_FIXTURE_GENERATED_HPP",
        "#define DBINFER_TESTS_TOKENIZER_FIXTURE_GENERATED_HPP",
        "",
        "#include <cstdint>",
        "#include <initializer_list>",
        "",
        "namespace dbinfer::tokenizer_fixture {",
        "",
        "struct Case {",
        "  std::initializer_list<std::uint8_t> input;",
        "  std::initializer_list<std::int32_t> ids;",
        "};",
        "",
        "inline const Case kCases[] = {",
    ]
    for data in CASES:
        ids = tokenize(data)
        id_str = "{" + ", ".join(str(i) for i in ids) + "}"
        lines.append(f"    {{{cpp_bytes(data)}, {id_str}}},")
    lines += [
        "};",
        "",
        "} // namespace dbinfer::tokenizer_fixture",
        "",
        "#endif // DBINFER_TESTS_TOKENIZER_FIXTURE_GENERATED_HPP",
        "",
    ]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {len(CASES)} cases to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
